### PR TITLE
Fix IE Issues

### PR DESCRIPTION
**Pull request by wgranger**
IE has some knows issues with Flexbox, so many of the changes here were in response to those issues. Also, IE doesn't support `.include()` when fetching an image src, so `.indexOf()` was used in place.

### CODE REVIEW

**Comment by srallen** [comment]
If you want to use newer spec like Array.includes(), there're lots of polyfills out there and cdn services. We use polyfill.io's cdn for polyfilling on PFE: https://polyfill.io/v2/docs/

**Comment by shaunanoordin** [comment]
I agree with Sarah; for functions, using polyfills is the way to go. 👍 

Actually, I think we already have a polyfill? https://github.com/zooniverse/liberating-the-liberator/blob/master/src/index.tpl.html#L7 But I never checked if it was working properly for all the features we need, so polyfill.io is probably the more reliable way to go.

The Flexbox issues, however, are a different story - let me take a look.

**Comment by wgranger** [comment]
Interesting. I'm not familiar with using one of these polyfill services, but the docs look thorough, so I can look into using an `.includes()` through a polyfill if that's a better option.

**Comment by srallen** [comment]
polyfill.io's defaults cover a lot, but some have to specified like Array.prototype.includes. Check out what we're doing with PFE: https://github.com/zooniverse/Panoptes-Front-End/blob/master/views/index.ejs#L73

**Comment by wgranger** [comment]
Well if that wasn't just the easiest thing I've ever done.

**Comment by shaunanoordin** [comment]
## PR Review
* This PR fixes compatibility issues with IE11 and MS Edge.
* Accessing the localhost on Win7+IE11 and Win10+Edge, we see that...
  * The main pages - Home, Classifier, About the Collection - look visually OK on a _desktop_ resolution. There are no visible issues with the layout or the like.
  * Basic interactions with the Classifier page have also tested OK, notably: adding Annotation.

Overall, this LGTM.

Side discussion:
@srallen You're right, it _is_ the same service (visiting the root Heroku domain shows the Polyfill.io website), and since I was the one who added the link (according to Blame), it means I somehow stumbled across the wrong URL for the correct service. To explain this discrepancy, I'm just going to say... a wizard did it.

### Status
LGTM, approving & merging. And remember, if this PR inexplicably causes problems in the future: https://youtu.be/sVgVB3qsySQ?t=16s

**Pull request merged**
