### PR TITLE
About the Collection Page

### PR DESCRIPTION
**Pull request by wgranger**
This PR creates the first pass at the About the Collection page. There is still some more content that will need to be added later, and the map page is still pending.

Wireframe can be found [here](https://projects.invisionapp.com/share/A3CXG9IK7#/screens/247475618_About).

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Not related to the PR, sorry, but OSX has added .DS_Store files to these commits somewhere.

**Comment by srallen** [comment]
Ignoring .DS_Store and other OS generated files should be added to zoo-reduxify's gitignore file. I didn't realize it wasn't in there since I have a global gitignore config setup on my machine.

**Comment by wgranger** [comment]
Wait. What's going on with the image above?

**Comment by shaunanoordin** [comment]
WHOOPS, uploaded the wrong picture in that previous post. In case you're wondering, that previous picture was the collection of insane packages available on Red Letter Day website. Take your kids sniping!

screen shot 2017-08-10 at 15 35 39
https://www.redletterdays.co.uk/experience/adventure/spy-survival-and-army-skills

**Comment by wgranger** [comment]
Ha. Ok. I was thinking maybe I fudged somewhere with my branch.

**Pull request merged**
