### PR TITLE
On successful Classification submission, reset the views/data then fetch next Subject

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
- With this PR, when a user _successfully_ submit a Classification, the app's data state is wiped clean, in preparation for the next Subject to be fetched.
- Alas, this is a bit difficult to test since the Subject queue I see on `localhost+zootester1` at the moment only has one Subject that repeats ad infinitum.
- I do see that the Annotations I made are correctly reset when the next (same) Subject is (re-)fetched, so that's good.

### For testing
Expected actions and results:
- User makes an Annotation on the Subject.
- User clicks DONE.
- Expected: there should be a POST to Panoptes's /classifications
- Expected: the Annotation that was made should disappear.
- Expected: there should be several GETs, to Panoptes /subjects and to the Caesar aggregation.
- Expected: a new Subject should appear (with any Previous Annotations for that Subject, if applicable.)

### Thoughts
- Submit Classifications in the Classifications duck was refactored - the Reducer now only performs data updates; all logic (esp. async logic) has been moved out to the Action creator.
- This PR doesn't really have a good handle of what to do when the Classification submission fails, however. Just an ugly alert... this goes on the ToDo.
- There's an open question of _what should I reset before the next Subject?_ e.g. should I run resetSubject() then fetchSubject(), or should fetchSubject() _implicitly_ reset the Subject data? Hmm, hmm.
- The placement of the reset-then-fetch-next-Subject logic is... uh... I feel there's something odd about it being in the Classifications reducer. I mean, it works, but my internal editor is shaking his head telling me that the flow of logic should be easier to see, at a glance, by other developers. His disdainful expression betrays no tidbits of advice, however.

### Bonus
- Temporary Workflow/Subject IDs are now placed in the config.
  - Wait, didn't I do this before? I have a feeling of deja-vu.

### Status
Ready for review, @wgranger

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Due to the merge of PR #105 , this PR needs to be rebased. (Special note on the `config.workflowId` repeat.) Feel free to continue analysing the code, but I'll post an update for this PR next week to make it merge-ready.

**Comment by shaunanoordin** [comment]
NYAAARGH, NO REBASE! We merge the master into the PR like true barbarians!

**Comment by wgranger** [comment]
Will this work alright without messing up the commit history somehow?

**Comment by shaunanoordin** [comment]
Fortunately, in this case, the merge master to PR wasn't bad at all. The commit just looks like this:

https://github.com/zooniverse/liberating-the-liberator/pull/103/commits/85910d81825b384c3035a754270d0d00264f8910

...and it was achieved using the GitHub 'resolve yer conflicts' tool.

I've seen messed up commit histories before so I understand your concern, but seeing how efficient _this merge_ was, I'm starting to think it was just _me_ who screwed up my previous attempts to merge master to branch using the CLI. 🤷‍♂️

**Comment by wgranger** [comment]
Ok. Worst case scenario, it can always be fixed, but it should probably be fine.

**Comment by shaunanoordin** [comment]
👍  Sweet!

I'm not too worried in any case, since I can see this PR's changes [looks clean](https://github.com/zooniverse/liberating-the-liberator/pull/103/files) (i.e. there are no repeats of your PR #105) so merging it would look equally clean. (Recommendation: _squash_ & merge for maximum cleanliness)

Anyway, I have no further updates for this PR, so feel free to give it a full review! 👌

**Comment by wgranger** [comment]
Beautiful. I have no complaints and have tested this out by adding another subject to our test subject set to check if another subject is correctly being fetched and served. All looks well. 

Thank you also for cleaning up some of the spaghetti code that leaked into a couple of those ducks. It looks much cleaner with the existential checks and separation of items into actions, reducers, etc.

**Pull request merged**
