### PR TITLE
Adjust App to Reflect Reduxify Changes

### PR DESCRIPTION
**Pull request by wgranger**
These changes were made based on a recent [update](https://github.com/zooniverse/zoo-reduxify/pull/9) to the Zooniverse reduxify starter repo. It could easily be that I missed or overlooked something in the process of this addition. Also, some of the app structure changed a bit based on that commit, so I'm open to changing it back should we decide to do so.

### CODE REVIEW

**Comment by wgranger** [comment]
Just saw some additions were also made to the reduxify repo concerning tree-shaking, so I can make those same changes in another commit here.

**Comment by shaunanoordin** [comment]
Thanks @wgranger ! I'm still reviewing these changes, and here are my current notes:
* Running on a dev environment seems to work great; I have very little concern so I'm just going to cross-reference the changes to ensure nothing hidden was missed.
* However, I have issues running `npm run build` - I'm still investigating what's happening here and trying to isolate whether it's just my machine.

Updates before the end of the UK day.

**Comment by shaunanoordin** [comment]
## PR Review
* This PR folds in the latest updates from our baseline, `zooniverse/zoo-reduxify`.
* Of note:
  * Folder structure has been updated, particularly with the introduction of **ducks** [[ref1]](https://github.com/erikras/ducks-modular-redux) [[ref2]](https://medium.com/@scbarrus/the-ducks-file-structure-for-redux-d63c41b7035c) to better organise our Redux logic.
  * The webpack dashboard has been enabled.
  * A new way of setting up **tests** (see About.jsx and About.spec.jsx) has been established.
* The following commands have tested OK: `npm start` (webpage loads correctly at localhost:3000), `npm run build` (files are packaged in the `/dist` folder with no errors on compile), and `npm test` (all tests - mostly those from About.jsx - pass correctly)

There's a minor styling issue with the Login/Logout button, but that's separate from the primary code migration this PR is responsible for.

### Status
LGTM, merging.

**Comment by shaunanoordin** [comment]
Just an update on the earlier problems with `npm run build` that I reported - looks like the issue was with my machine setup, so it was solved by dumping my local stuff and rebuilding from scratch. 👌

**Pull request merged**
