### PR TITLE
About Timeline

### PR DESCRIPTION
**Pull request by wgranger**
This is a relatively large PR, but there was some SVG magic needed to get animations to work properly. It appears to be working in all browsers aside from IE (where a bit more work is necessary). If hesitant to merge with how the timeline functions with IE, this can become a WIP. Otherwise, an issue can be opened once merged. 

This was my first foray into SVG animations, so there might be some code that can be cleaned up. The Text component was created to allow dynamic, multi-line SVG text objects with `tspan`.

### CODE REVIEW

**Comment by srallen** [comment]
You might want to look into a react chart library based on d3.js so that you don't have to manually write all of the animation handlers for SVG. d3.js is a standard SVG animating library.

**Comment by srallen** [comment]
Good article on state of d3.js animation and use in a react app: https://hackernoon.com/how-and-why-to-use-d3-with-react-d239eb1ea274

**Comment by shaunanoordin** [comment]
Do we need those h2 and div styles? I honestly can't tell.

```
src/styles/components/about-collection.styl:
...
  &__timeline
    margin: 2.5em

<<<<<<< about-timeline
=======
    h2
      @extend .secondary-head
      font-size: 1.5em
      letter-spacing: 0.05em
      text-transform: lowercase

    div
      flex-wrap: wrap
      font-size: 0.75em
      justify-content: center
      margin: 1em 2em

>>>>>>> master
```

**Comment by shaunanoordin** [comment]
I just saw those updates; only need to resolve that conflict before this can be merged! 👍

**Comment by wgranger** [comment]
Oh, right. Forgot about that conflict. Those were holdover styles from the initial about page, so they are unnecessary.

**Comment by shaunanoordin** [comment]
Niiice!

**Pull request merged**
